### ISSUE TITLE
超商代碼繳費截止時間與實際使用不同

### ISSUE THREAD

**Issue by cras4202tw** [ECPay/WHMCS_PHP#1]
『繳費截止時間』的說明是：≤ 100 為天數，> 100 為分鐘

但實際上我填入 3 會得到只有 3 分鐘的到期時間，而不是 3 天
我填入 4320 才會是 3 天

根據介接文件：
[https://www.ecpay.com.tw/Content/files/ecpay_011.pdf](https://www.ecpay.com.tw/Content/files/ecpay_011.pdf)
第 16 頁對於 StoreExpireDate 的說明，若為 CVS 付款則是以分鐘為單位

**Comment by AllennChang** [comment]
您好, 感謝您的反應, CVS 付款則是以分鐘為單位喔
![image](https://user-images.githubusercontent.com/21259508/69215347-6c6f5880-0ba4-11ea-83f2-d060ebe02bd6.png)
