### ISSUE TITLE
付款完成後無法完成訂單

### ISSUE THREAD

**Issue by boringwolf** [ECPay/WHMCS_PHP#4]
串接付款完成後無法 callback 付款完成狀態
目前使用 whmcs 8.0.2
請問是因為 whmcs 版本問題還是 綠界有更新api 導致

你們會更新 還是我要自行處理

**Comment by AllennChang** [comment]
您好, 感謝您的提問, 經確認綠界API 回傳的部份沒有變動,  
目前綠界SDK 只支援WHMCS 6.0 , 新版本的WHMCS8.0.2 目前不支援, 
未來是否更新支援WHMCS8.0.2版本, 會再請開發團隊進行研究,

**Comment by boringwolf** [comment]
好 感謝，希望早日有好消息！
