### ISSUE TITLE
不好意思

### ISSUE THREAD

**Issue by boringwolf** [ECPay/WHMCS_PHP#5]
如果需要支援8.0的話，最快甚麼時候能定案呢，還是目前都還是未知數。

**Comment by AllennChang** [comment]
您好, 目前開發團隊還在進行其它研發項目, 目前還無法定案, 最快開發時程也要明年年中以後, 
因此若您有時程上的需求, 建議您可以試著自行串接我們的API 及參考我們的SDK .
https://www.ecpay.com.tw/Service/API_Dwnld 
若造成您的不便 深感抱歉, 歡迎有任何問題, 再跟我們反應, 感謝您
